const plotData = [
  {
    property1: "Default",
    showSold: true,
    plot: "Total Plot: 3",
    heading: "Chunikhel Plotting",
    available: "Available: 2",
    showAvailable: true,
    location: "Chunikhel, Budhanilkhantha, Kathmandu",
    house: true,
    road: true,
    drain: true,
    ft: true,
    Sold: "Sold: 1",
    road2: "12-13 ft",
    totalPlot: true,
    measurement: "0-3-1-2",
  },
  {
    property1: "Default",
    showSold: true,
    plot: "Total Plot: 3",
    heading: "Gayabari Plotting",
    available: "Available: 2",
    showAvailable: true,
    location: "Chunikhel, Budhanilkhantha, Kathmandu",
    house: true,
    road: true,
    drain: true,
    ft: true,
    Sold: "Sold: 1",
    road2: "12-13 ft",
    totalPlot: true,
    measurement: "0-3-1-2",
  },
  {
    property1: "Default",
    showSold: true,
    plot: "Total Plot: 3",
    heading: "Chunikhel Plotting",
    available: "Available: 2",
    showAvailable: true,
    location: "Chunikhel, Budhanilkhantha, Kathmandu",
    house: true,
    road: true,
    drain: true,
    ft: true,
    Sold: "Sold: 1",
    road2: "12-13 ft",
    totalPlot: true,
    measurement: "0-3-1-2",
  },
  {
    property1: "Default",
    showSold: true,
    plot: "Total Plot: 3",
    heading: "Chunikhel Plotting",
    available: "Available: 2",
    showAvailable: true,
    location: "Chunikhel, Budhanilkhantha, Kathmandu",
    house: true,
    road: true,
    drain: true,
    ft: true,
    Sold: "Sold: 1",
    road2: "12-13 ft",
    totalPlot: true,
    measurement: "0-3-1-2",
  },
  {
    property1: "Default",
    showSold: true,
    plot: "Total Plot: 3",
    heading: "Chunikhel Plotting",
    available: "Available: 2",
    showAvailable: true,
    location: "Chunikhel, Budhanilkhantha, Kathmandu",
    house: true,
    road: true,
    drain: true,
    ft: true,
    Sold: "Sold: 1",
    road2: "12-13 ft",
    totalPlot: true,
    measurement: "0-3-1-2",
  },
  {
    property1: "Default",
    showSold: true,
    plot: "Total Plot: 3",
    heading: "Chunikhel Plotting",
    available: "Available: 2",
    showAvailable: true,
    location: "Chunikhel, Budhanilkhantha, Kathmandu",
    house: true,
    road: true,
    drain: true,
    ft: true,
    Sold: "Sold: 1",
    road2: "12-13 ft",
    totalPlot: true,
    measurement: "0-3-1-2",
  },
  {
    property1: "Default",
    showSold: true,
    plot: "Total Plot: 3",
    heading: "Chunikhel Plotting",
    available: "Available: 2",
    showAvailable: true,
    location: "Chunikhel, Budhanilkhantha, Kathmandu",
    house: true,
    road: true,
    drain: true,
    ft: true,
    Sold: "Sold: 1",
    road2: "12-13 ft",
    totalPlot: true,
    measurement: "0-3-1-2",
  },
 
  
];

export default plotData;
